/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserRouteImport } from './routes/user/route'
import { Route as LoginRouteImport } from './routes/login/route'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as RouteImport } from './routes/route'
import { Route as UserUsersRouteImport } from './routes/user/users/route'
import { Route as UserProfileRouteImport } from './routes/user/profile/route'
import { Route as UserModelsRouteImport } from './routes/user/models/route'
import { Route as UserGiftsRouteImport } from './routes/user/gifts/route'
import { Route as UserDialogsRouteImport } from './routes/user/dialogs/route'
import { Route as AdminUsersRouteImport } from './routes/admin/users/route'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions/route'
import { Route as AdminTariffsRouteImport } from './routes/admin/tariffs/route'
import { Route as AdminProfileRouteImport } from './routes/admin/profile/route'
import { Route as AdminModelsRouteImport } from './routes/admin/models/route'
import { Route as AdminGiftsRouteImport } from './routes/admin/gifts/route'
import { Route as AdminDialogsRouteImport } from './routes/admin/dialogs/route'
import { Route as AdminChattersRouteImport } from './routes/admin/chatters/route'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins/route'
import { Route as UserDialogsUserIdRouteImport } from './routes/user/dialogs/$userId/route'
import { Route as AdminDialogsUserIdRouteImport } from './routes/admin/dialogs/$userId/route'

// Create/Update Routes

const UserRouteRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRoute,
} as any)

const LoginRouteRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const RouteRoute = RouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserUsersRouteRoute = UserUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => UserRouteRoute,
} as any)

const UserProfileRouteRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRouteRoute,
} as any)

const UserModelsRouteRoute = UserModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => UserRouteRoute,
} as any)

const UserGiftsRouteRoute = UserGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => UserRouteRoute,
} as any)

const UserDialogsRouteRoute = UserDialogsRouteImport.update({
  id: '/dialogs',
  path: '/dialogs',
  getParentRoute: () => UserRouteRoute,
} as any)

const AdminUsersRouteRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminTransactionsRouteRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminTariffsRouteRoute = AdminTariffsRouteImport.update({
  id: '/tariffs',
  path: '/tariffs',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminProfileRouteRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminModelsRouteRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminGiftsRouteRoute = AdminGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminDialogsRouteRoute = AdminDialogsRouteImport.update({
  id: '/dialogs',
  path: '/dialogs',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminChattersRouteRoute = AdminChattersRouteImport.update({
  id: '/chatters',
  path: '/chatters',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminAdminsRouteRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRouteRoute,
} as any)

const UserDialogsUserIdRouteRoute = UserDialogsUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UserDialogsRouteRoute,
} as any)

const AdminDialogsUserIdRouteRoute = AdminDialogsUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminDialogsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RouteImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/chatters': {
      id: '/admin/chatters'
      path: '/chatters'
      fullPath: '/admin/chatters'
      preLoaderRoute: typeof AdminChattersRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/dialogs': {
      id: '/admin/dialogs'
      path: '/dialogs'
      fullPath: '/admin/dialogs'
      preLoaderRoute: typeof AdminDialogsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/gifts': {
      id: '/admin/gifts'
      path: '/gifts'
      fullPath: '/admin/gifts'
      preLoaderRoute: typeof AdminGiftsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/tariffs': {
      id: '/admin/tariffs'
      path: '/tariffs'
      fullPath: '/admin/tariffs'
      preLoaderRoute: typeof AdminTariffsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/user/dialogs': {
      id: '/user/dialogs'
      path: '/dialogs'
      fullPath: '/user/dialogs'
      preLoaderRoute: typeof UserDialogsRouteImport
      parentRoute: typeof UserRouteImport
    }
    '/user/gifts': {
      id: '/user/gifts'
      path: '/gifts'
      fullPath: '/user/gifts'
      preLoaderRoute: typeof UserGiftsRouteImport
      parentRoute: typeof UserRouteImport
    }
    '/user/models': {
      id: '/user/models'
      path: '/models'
      fullPath: '/user/models'
      preLoaderRoute: typeof UserModelsRouteImport
      parentRoute: typeof UserRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRouteImport
    }
    '/user/users': {
      id: '/user/users'
      path: '/users'
      fullPath: '/user/users'
      preLoaderRoute: typeof UserUsersRouteImport
      parentRoute: typeof UserRouteImport
    }
    '/admin/dialogs/$userId': {
      id: '/admin/dialogs/$userId'
      path: '/$userId'
      fullPath: '/admin/dialogs/$userId'
      preLoaderRoute: typeof AdminDialogsUserIdRouteImport
      parentRoute: typeof AdminDialogsRouteImport
    }
    '/user/dialogs/$userId': {
      id: '/user/dialogs/$userId'
      path: '/$userId'
      fullPath: '/user/dialogs/$userId'
      preLoaderRoute: typeof UserDialogsUserIdRouteImport
      parentRoute: typeof UserDialogsRouteImport
    }
  }
}

// Create and export the route tree

interface AdminDialogsRouteRouteChildren {
  AdminDialogsUserIdRouteRoute: typeof AdminDialogsUserIdRouteRoute
}

const AdminDialogsRouteRouteChildren: AdminDialogsRouteRouteChildren = {
  AdminDialogsUserIdRouteRoute: AdminDialogsUserIdRouteRoute,
}

const AdminDialogsRouteRouteWithChildren =
  AdminDialogsRouteRoute._addFileChildren(AdminDialogsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAdminsRouteRoute: typeof AdminAdminsRouteRoute
  AdminChattersRouteRoute: typeof AdminChattersRouteRoute
  AdminDialogsRouteRoute: typeof AdminDialogsRouteRouteWithChildren
  AdminGiftsRouteRoute: typeof AdminGiftsRouteRoute
  AdminModelsRouteRoute: typeof AdminModelsRouteRoute
  AdminProfileRouteRoute: typeof AdminProfileRouteRoute
  AdminTariffsRouteRoute: typeof AdminTariffsRouteRoute
  AdminTransactionsRouteRoute: typeof AdminTransactionsRouteRoute
  AdminUsersRouteRoute: typeof AdminUsersRouteRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminsRouteRoute: AdminAdminsRouteRoute,
  AdminChattersRouteRoute: AdminChattersRouteRoute,
  AdminDialogsRouteRoute: AdminDialogsRouteRouteWithChildren,
  AdminGiftsRouteRoute: AdminGiftsRouteRoute,
  AdminModelsRouteRoute: AdminModelsRouteRoute,
  AdminProfileRouteRoute: AdminProfileRouteRoute,
  AdminTariffsRouteRoute: AdminTariffsRouteRoute,
  AdminTransactionsRouteRoute: AdminTransactionsRouteRoute,
  AdminUsersRouteRoute: AdminUsersRouteRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface UserDialogsRouteRouteChildren {
  UserDialogsUserIdRouteRoute: typeof UserDialogsUserIdRouteRoute
}

const UserDialogsRouteRouteChildren: UserDialogsRouteRouteChildren = {
  UserDialogsUserIdRouteRoute: UserDialogsUserIdRouteRoute,
}

const UserDialogsRouteRouteWithChildren =
  UserDialogsRouteRoute._addFileChildren(UserDialogsRouteRouteChildren)

interface UserRouteRouteChildren {
  UserDialogsRouteRoute: typeof UserDialogsRouteRouteWithChildren
  UserGiftsRouteRoute: typeof UserGiftsRouteRoute
  UserModelsRouteRoute: typeof UserModelsRouteRoute
  UserProfileRouteRoute: typeof UserProfileRouteRoute
  UserUsersRouteRoute: typeof UserUsersRouteRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserDialogsRouteRoute: UserDialogsRouteRouteWithChildren,
  UserGiftsRouteRoute: UserGiftsRouteRoute,
  UserModelsRouteRoute: UserModelsRouteRoute,
  UserProfileRouteRoute: UserProfileRouteRoute,
  UserUsersRouteRoute: UserUsersRouteRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof RouteRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/user': typeof UserRouteRouteWithChildren
  '/admin/admins': typeof AdminAdminsRouteRoute
  '/admin/chatters': typeof AdminChattersRouteRoute
  '/admin/dialogs': typeof AdminDialogsRouteRouteWithChildren
  '/admin/gifts': typeof AdminGiftsRouteRoute
  '/admin/models': typeof AdminModelsRouteRoute
  '/admin/profile': typeof AdminProfileRouteRoute
  '/admin/tariffs': typeof AdminTariffsRouteRoute
  '/admin/transactions': typeof AdminTransactionsRouteRoute
  '/admin/users': typeof AdminUsersRouteRoute
  '/user/dialogs': typeof UserDialogsRouteRouteWithChildren
  '/user/gifts': typeof UserGiftsRouteRoute
  '/user/models': typeof UserModelsRouteRoute
  '/user/profile': typeof UserProfileRouteRoute
  '/user/users': typeof UserUsersRouteRoute
  '/admin/dialogs/$userId': typeof AdminDialogsUserIdRouteRoute
  '/user/dialogs/$userId': typeof UserDialogsUserIdRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof RouteRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/user': typeof UserRouteRouteWithChildren
  '/admin/admins': typeof AdminAdminsRouteRoute
  '/admin/chatters': typeof AdminChattersRouteRoute
  '/admin/dialogs': typeof AdminDialogsRouteRouteWithChildren
  '/admin/gifts': typeof AdminGiftsRouteRoute
  '/admin/models': typeof AdminModelsRouteRoute
  '/admin/profile': typeof AdminProfileRouteRoute
  '/admin/tariffs': typeof AdminTariffsRouteRoute
  '/admin/transactions': typeof AdminTransactionsRouteRoute
  '/admin/users': typeof AdminUsersRouteRoute
  '/user/dialogs': typeof UserDialogsRouteRouteWithChildren
  '/user/gifts': typeof UserGiftsRouteRoute
  '/user/models': typeof UserModelsRouteRoute
  '/user/profile': typeof UserProfileRouteRoute
  '/user/users': typeof UserUsersRouteRoute
  '/admin/dialogs/$userId': typeof AdminDialogsUserIdRouteRoute
  '/user/dialogs/$userId': typeof UserDialogsUserIdRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof RouteRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/user': typeof UserRouteRouteWithChildren
  '/admin/admins': typeof AdminAdminsRouteRoute
  '/admin/chatters': typeof AdminChattersRouteRoute
  '/admin/dialogs': typeof AdminDialogsRouteRouteWithChildren
  '/admin/gifts': typeof AdminGiftsRouteRoute
  '/admin/models': typeof AdminModelsRouteRoute
  '/admin/profile': typeof AdminProfileRouteRoute
  '/admin/tariffs': typeof AdminTariffsRouteRoute
  '/admin/transactions': typeof AdminTransactionsRouteRoute
  '/admin/users': typeof AdminUsersRouteRoute
  '/user/dialogs': typeof UserDialogsRouteRouteWithChildren
  '/user/gifts': typeof UserGiftsRouteRoute
  '/user/models': typeof UserModelsRouteRoute
  '/user/profile': typeof UserProfileRouteRoute
  '/user/users': typeof UserUsersRouteRoute
  '/admin/dialogs/$userId': typeof AdminDialogsUserIdRouteRoute
  '/user/dialogs/$userId': typeof UserDialogsUserIdRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/user'
    | '/admin/admins'
    | '/admin/chatters'
    | '/admin/dialogs'
    | '/admin/gifts'
    | '/admin/models'
    | '/admin/profile'
    | '/admin/tariffs'
    | '/admin/transactions'
    | '/admin/users'
    | '/user/dialogs'
    | '/user/gifts'
    | '/user/models'
    | '/user/profile'
    | '/user/users'
    | '/admin/dialogs/$userId'
    | '/user/dialogs/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/user'
    | '/admin/admins'
    | '/admin/chatters'
    | '/admin/dialogs'
    | '/admin/gifts'
    | '/admin/models'
    | '/admin/profile'
    | '/admin/tariffs'
    | '/admin/transactions'
    | '/admin/users'
    | '/user/dialogs'
    | '/user/gifts'
    | '/user/models'
    | '/user/profile'
    | '/user/users'
    | '/admin/dialogs/$userId'
    | '/user/dialogs/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/user'
    | '/admin/admins'
    | '/admin/chatters'
    | '/admin/dialogs'
    | '/admin/gifts'
    | '/admin/models'
    | '/admin/profile'
    | '/admin/tariffs'
    | '/admin/transactions'
    | '/admin/users'
    | '/user/dialogs'
    | '/user/gifts'
    | '/user/models'
    | '/user/profile'
    | '/user/users'
    | '/admin/dialogs/$userId'
    | '/user/dialogs/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
  UserRouteRoute: typeof UserRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
  UserRouteRoute: UserRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/login",
        "/user"
      ]
    },
    "/": {
      "filePath": "route.tsx"
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/admins",
        "/admin/chatters",
        "/admin/dialogs",
        "/admin/gifts",
        "/admin/models",
        "/admin/profile",
        "/admin/tariffs",
        "/admin/transactions",
        "/admin/users"
      ]
    },
    "/login": {
      "filePath": "login/route.tsx"
    },
    "/user": {
      "filePath": "user/route.tsx",
      "children": [
        "/user/dialogs",
        "/user/gifts",
        "/user/models",
        "/user/profile",
        "/user/users"
      ]
    },
    "/admin/admins": {
      "filePath": "admin/admins/route.tsx",
      "parent": "/admin"
    },
    "/admin/chatters": {
      "filePath": "admin/chatters/route.tsx",
      "parent": "/admin"
    },
    "/admin/dialogs": {
      "filePath": "admin/dialogs/route.tsx",
      "parent": "/admin",
      "children": [
        "/admin/dialogs/$userId"
      ]
    },
    "/admin/gifts": {
      "filePath": "admin/gifts/route.tsx",
      "parent": "/admin"
    },
    "/admin/models": {
      "filePath": "admin/models/route.tsx",
      "parent": "/admin"
    },
    "/admin/profile": {
      "filePath": "admin/profile/route.tsx",
      "parent": "/admin"
    },
    "/admin/tariffs": {
      "filePath": "admin/tariffs/route.tsx",
      "parent": "/admin"
    },
    "/admin/transactions": {
      "filePath": "admin/transactions/route.tsx",
      "parent": "/admin"
    },
    "/admin/users": {
      "filePath": "admin/users/route.tsx",
      "parent": "/admin"
    },
    "/user/dialogs": {
      "filePath": "user/dialogs/route.tsx",
      "parent": "/user",
      "children": [
        "/user/dialogs/$userId"
      ]
    },
    "/user/gifts": {
      "filePath": "user/gifts/route.tsx",
      "parent": "/user"
    },
    "/user/models": {
      "filePath": "user/models/route.tsx",
      "parent": "/user"
    },
    "/user/profile": {
      "filePath": "user/profile/route.tsx",
      "parent": "/user"
    },
    "/user/users": {
      "filePath": "user/users/route.tsx",
      "parent": "/user"
    },
    "/admin/dialogs/$userId": {
      "filePath": "admin/dialogs/$userId/route.tsx",
      "parent": "/admin/dialogs"
    },
    "/user/dialogs/$userId": {
      "filePath": "user/dialogs/$userId/route.tsx",
      "parent": "/user/dialogs"
    }
  }
}
ROUTE_MANIFEST_END */
